stages:
  - test

test-job:
  stage: test
  image: rust:latest
  before_script:
    - sed -i 's|ssh://git@git.slock.it/|https://:$CI_ACCESS_TOKEN@git.slock.it/|' Cargo.toml
  script:
    - cargo test --verbose
  only:
    - merge_requests
    - main
    - feature/ASDK-82
