include:
  - template: Security/SAST.gitlab-ci.yml
  - template: Security/Secret-Detection.gitlab-ci.yml
  - project: 'build-images/synopsys-detect'
    ref: main
    file: '/templates/.gitlab-ci-blackduck-intelligent.yml'
  - project: 'build-images/synopsys-detect'
    ref: main
    file: '/templates/.gitlab-ci-blackduck-signature.yml'
  - local: "wrappers/nodejs/publish.yml"
  - local: "plugins/askar/wrappers/nodejs/publish.yml"

stages:
  - scan
  - build
  - lint
  - test
  - release

variables:
  RUST_VERSION: "1.82.0"
  NODE_VERSION: "20.18.0"
  VERSION_REGEX: /^[0-9]+\.[0-9]+\.[0-9]+$/
  REGISTRY: "git.slock.it/api/v4/projects/1387/packages/npm/"
  REGISTRY_URL: "https://git.slock.it/api/v4/projects/1387/packages/npm/"


# Shared configurations

.cargo_local_deps_script: &cargo_local_deps_script
  - sed -i "s|ssh://git@git.slock.it/|https://gitlab-ci-token:${CI_JOB_TOKEN}@git.slock.it/|" Cargo.toml

.rust_job_configs: &rust_job_configs
  image: rust:${RUST_VERSION}
  before_script:
    - *cargo_local_deps_script

.nodejs_job_configs: &nodejs_job_configs
  image: node:${NODE_VERSION}
  before_script:
    - curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain ${RUST_VERSION}
    - source "$HOME/.cargo/env"
    - *cargo_local_deps_script

.black_duck_scan: &black_duck_scan
  stage: scan
  before_script:
    - curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain ${RUST_VERSION}
    - source "$HOME/.cargo/env"
    - *cargo_local_deps_script
    - cargo generate-lockfile

# Scan stage

black duck scan branches:
  <<: *black_duck_scan

black duck signature scan branches:
  <<: *black_duck_scan

black duck scan tags:
  <<: *black_duck_scan

black duck signature scan tags:
  <<: *black_duck_scan

semgrep-sast:
  stage: scan
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_COMMIT_REF_NAME == "main"'
      changes:
        - '**/*.rs'

secret_detection:
  stage: scan
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_COMMIT_REF_NAME == "main"'
      changes:
        - '**/*'

dependency_scanning:
  <<: *rust_job_configs
  stage: scan
  script:
    - cargo install gitlab-cargo-audit
    - gitlab-cargo-audit --output-path gl-dependency-scanning-report.json
  artifacts:
    when: always
    reports:
      dependency_scanning: gl-dependency-scanning-report.json
  only:
    - merge_requests
    - main

# Build stage

build-job:
  <<: *rust_job_configs
  stage: build
  script:
    - cargo build --all-features --workspace --exclude wasm
  only:
    - merge_requests
    - main

nodejs-wrapper-build-job:
  <<: *nodejs_job_configs
  stage: build
  script:
    - npm i --prefix wrappers/nodejs
    - npm run build --prefix wrappers/nodejs
  only:
    - merge_requests
    - main

nodejs-demo-build-job:
  <<: *nodejs_job_configs
  stage: build
  script:
    - npm config set "@equstng:registry" 'https://${CI_SERVER_HOST}/api/v4/projects/${CI_PROJECT_ID}/packages/npm/'
    - npm config set -- '//${CI_SERVER_HOST}/api/v4/projects/${CI_PROJECT_ID}/packages/npm/:_authToken' "${CI_JOB_TOKEN}"
    - npm i -ignore-scripts --prefix wrappers/nodejs
    - npm run build:debug --prefix wrappers/nodejs
    - npm i -ignore-scripts --prefix plugins/askar/wrappers/nodejs
    - npm run build --prefix plugins/askar/wrappers/nodejs
    - npm i --prefix demos/nodejs/oid4vc
    - npm run build --prefix demos/nodejs/oid4vc
  only:
    - merge_requests
    - main

doc-build-job:
  <<: *rust_job_configs
  stage: build
  script:
    - RUSTDOCFLAGS="-D warnings" cargo doc --no-deps --workspace --all-features
  only:
    - merge_requests
    - main

# Lint stage

check-format-job:
  <<: *rust_job_configs
  stage: lint
  script:
    - rustup component add rustfmt
    - cargo fmt --all -- --check
  only:
    - merge_requests
    - main

lint-job:
  <<: *rust_job_configs
  stage: lint
  script:
    - rustup component add clippy
    - cargo clippy --workspace --exclude wasm --all-targets --all-features -- -Dwarnings
  only:
    - merge_requests
    - main

# Test stage

test-with-coverage-job:
  <<: *rust_job_configs
  stage: test
  script:
    - cargo install cargo-tarpaulin
    - cargo tarpaulin --skip-clean --timeout 180 --all-features --exclude-files "demos/*" --exclude-files "wrappers/*" --fail-under 60 -o Html
  coverage: '/^\d+.\d+% coverage/'
  artifacts:
    paths:
      - tarpaulin-report.html
  only:
    - merge_requests
    - main

nodejs-test-job:
  <<: *nodejs_job_configs
  stage: test
  script:
    - npm i --prefix wrappers/nodejs
    - npm run build:debug --prefix wrappers/nodejs
    - npm run test --prefix wrappers/nodejs
  only:
    - merge_requests
    - main

askar-plugin-nodejs-test-job:
  <<: *nodejs_job_configs
  stage: test
  script:
    - npm i --prefix wrappers/nodejs
    - npm run build:debug --prefix wrappers/nodejs
    - npm i --prefix plugins/askar/wrappers/nodejs
    - npm run build --prefix plugins/askar/wrappers/nodejs
    - npm run test --prefix plugins/askar/wrappers/nodejs
  only:
    - merge_requests
    - main

wasm-test-job:
  image: cimg/node:${NODE_VERSION}-browsers
  before_script:
    - curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain ${RUST_VERSION}
    - source "$HOME/.cargo/env"
    - *cargo_local_deps_script
    - sudo apt-get update
    - sudo apt-get install -y clang
    - curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
  stage: test
  script:
    - cd wrappers/wasm
    - npm install
    - make
    - cd ./test
    - npm run test
  only:
    - merge_requests
    - main

# Release stage
release_artifacts_job:
  <<: *rust_job_configs
  stage: release
  script:
    - cargo install cargo-sbom
    - cargo install cargo-audit
    - cargo sbom &>  SBOM.auto.out
    - cargo audit &> AUDIT.auto.out || true
    - cargo doc --no-deps
    - tar -cvz -f API.auto.tar.gz target/doc/agent_sdk/
  artifacts:
    paths:
      - SBOM.auto.out
      - AUDIT.auto.out
      - API.auto.tar.gz
  rules:
    - if: $CI_COMMIT_TAG && $CI_COMMIT_TAG =~ $VERSION_REGEX
      when: always
    - when: never