[package]
name = "agent-sdk"
version = "0.1.0"
edition = "2021"

[dependencies]
oauth2 = "4.4.2"
oid4vci = { git = "https://github.com/spruceid/oid4vci-rs", version = "0.1.0" }
oidc4vp = { git = "ssh://git@gitlab.dsr-corporation.com/dsr-blockchain/oid4vp-rs", version = "0.1.0", branch = "oidc4vp-new-impl" }
serde_json = "1.0.120"
ssi = "0.7.0"
rand = "0.8.5"
ed25519-dalek = "2.1.1"
random-string = "1.1.0"
serde = { version = "1.0.204", features = ["derive"] }
p256 = "0.13.2"
did-method-key = "0.2.2"

[dev-dependencies]
tokio = { version = "1.25.0", features = ["macros"] }
