[workspace]
members = [
    "demos/oid4vc/issuer",
    "demos/oid4vc/verifier",
    "demos/oid4vc/holder",
    "demos/multi-thread",
    "plugins/askar",
    "wrappers/nodejs",
    "common-macros",
]

[package]
name = "agent-sdk"
version = "0.3.2"
edition = "2021"
rust-version = "1.79"

[dependencies]
common-macros = { path = "./common-macros" }

oid4vci = { git = "ssh://git@git.slock.it/open-source/oid4vci-rs.git", rev = "73848acc" }
oid4vp = { git = "ssh://git@git.slock.it/open-source/oid4vp-rs.git", rev = "75a456b9" }
sd-jwt-rs = { git = "ssh://git@git.slock.it/open-source/sd-jwt-rust.git", rev = "05e6866e" }

oauth2 = "4.4.2"
serde_json = "1.0.120"
ssi = "0.7.0"
rand = { version = "0.8.5", optional = true }
ed25519-dalek = { version = "2.1.1", optional = true }
random-string = "1.1.0"
time = { version = "0.3.29", features = ["serde"] }
serde = { version = "1.0.204", features = ["derive"] }
p256 = { version = "0.13.2", optional = true }
did-method-key = "0.2.2"
did-web = "0.2.2"
ssi-dids = "0.1.1"
ssi-ldp = "0.3.2"
iref = "2.2.3"
futures = "0.3.30"
base64 = "0.22.1"
jsonwebtoken = "9.3.0"
async-trait = "0.1.81"
strum_macros = "0.26.4"
strum = { version = "0.26.3", features = ["derive"] }
reqwest = { version = "0.11", features = ["rustls-tls"] }
uuid = { version = "1.10.0", features = ["v4"] }
url = "2.5.2"
anyhow = "1.0.86"
async-rwlock = "1.3.0"
tracing = { version = "0.1.40", features = ["attributes", "release_max_level_warn"] }
snafu = "0.8.4"
regex = "1.11.0"
mime = "0.3.17"
chrono = "0.4.38"

[dev-dependencies]
serde_urlencoded = "0.7.1"
tokio = { version = "1.25.0", features = ["macros"] }
mockall = "0.13.0"
mockito = "1.5.0"
rstest = "0.22.0"
async-mutex = "1.4.0"
rand = { version = "0.8.5" }
ed25519-dalek = { version = "2.1.1" }
p256 = { version = "0.13.2" }

[features]
in-memory = ["dep:rand", "dep:ed25519-dalek", "dep:p256"]
