[package]
name = "agent-sdk"
version = "0.1.0"
edition = "2021"

[dependencies]
oid4vci = { git = "ssh://git@git.slock.it/open-source/oid4vci-rs", branch = "asdk-main" }
oid4vp = { git = "ssh://git@git.slock.it/open-source/oid4vp-rs.git", branch = "asdk-main" }
sd-jwt-rs = { git = "ssh://git@git.slock.it/open-source/sd-jwt-rust.git", branch = "asdk-main" }

oauth2 = "4.4.2"
serde_json = "1.0.120"
ssi = "0.7.0"
rand = "0.8.5"
ed25519-dalek = "2.1.1"
random-string = "1.1.0"
time = { version = "0.3.29", features = ["serde"] }
serde = { version = "1.0.204", features = ["derive"] }
p256 = "0.13.2"
did-method-key = "0.2.2"
futures = "0.3.30"
base64 = "0.22.1"
jsonwebtoken = "9.3.0"
async-trait = "0.1.81"
strum_macros = "0.26.4"
strum = { version = "0.26.3", features = ["derive"] }
thiserror = "1.0.63"
reqwest = "0.11"
uuid = { version = "1.10.0", features = ["v4"] }
url = "2.5.2"
anyhow = "1.0.86"

[dev-dependencies]
tokio = { version = "1.25.0", features = ["macros"] }
mockito = "1.5.0"
mockall = "0.13.0"
