use async_trait::async_trait;
use snafu::{Location, Snafu};
use std::collections::HashMap;
use std::fmt::Debug;

use crate::crypto;
use crate::kms::Error as KmsError;
use crate::vault::Error as VaultError;
use crate::vc::{
    formats::Error as VCError, metadata::Error as MetadataError, pop, pop::Error as ProofError,
    Claims, Credential, CredentialMetadata, Presentation, VCFormat,
};

/// A metadata for the `Issuer`.
///
/// Encapsulates all necessary data needed to handle issuance of the `Credential`s.
///
/// One `IssuerMetadata` supports multiple [CredentialDefinition]s.
#[derive(Debug, PartialEq, Clone)]
pub struct IssuerMetadata {
    pub issuer_id: String,
    pub cred_defs: Vec<CredentialDefinition>,
    pub protocol_data: Option<IssuerMetadataData>, // Protocol specific
}

/// A protocol-specific data for the `Issuer`.
///
/// *NOTE*: will be extended in the next releases.
#[derive(Debug, PartialEq, Clone)]
pub struct IssuerMetadataData {}

/// A `CredentialDefinition` for the `Issuer`.
///
/// Defines the Credential Schema and enlists the claims expected in the corresponding `Credential`.
/// Contains other various data necessary for creation of `Credential` as well.
#[derive(Debug, Clone, PartialEq)]
pub struct CredentialDefinition {
    pub cred_def_id: String,
    pub format: VCFormat,
    pub claims: HashMap<String, Display>,
    pub supported_proofs: Option<HashMap<pop::Format, Vec<crypto::Alg>>>,
    pub supported_signing_algs: Option<Vec<crypto::Alg>>,
    pub display: Option<Display>,
    pub protocol_data: Option<CredentialDefinitionData>, // Protocol specific
    pub key_metadata: KeyMetadata,
}

/// A helper struct for handling Keys and DIDs for the services.
///
/// Contains `DIDURL` of the party and the corresponding `KID` to access the key.
#[derive(Debug, PartialEq, Clone)]
pub struct KeyMetadata {
    pub did_url: String,
    pub kid: String,
}

/// A metadata for the `Holder`.
///
/// Encapsulates all necessary data needed to issue a `Credential`.
///
/// One `IssuerMetadata` supports multiple [CredentialDefinition]s.
#[derive(Debug, PartialEq, Clone)]
pub struct HolderMetadata {
    pub client_id: String,
    pub key_metadata: KeyMetadata,
}

/// A format-specific data for the `CredentialDefinition`.
///
/// *NOTE*: will be extended in the next releases.
#[derive(Debug, PartialEq, Clone)]
#[non_exhaustive]
pub enum CredentialDefinitionData {
    SdJwt {
        vct: String,
        disclosures: Vec<String>,
        lifetime: Option<time::Duration>,
    },
}

/// A `CredentialOffer` entity.
///
/// Contains the data related to offered `Credential`.
///
/// Generated by `Issuer` to be used later by `Holder` to build a proper `CredentialRequest`.
///
/// *NOTE*: will be extended in the next releases.
#[derive(Debug, PartialEq, Clone)]
pub struct CredentialOffer {
    pub cred_offer_id: Option<String>,
    pub issuer_id: String,
    pub cred_def_id: String,
    pub content: CredentialOfferContent,
    pub protocol_data: Option<CredentialOfferData>, // Protocol specific
}

/// A struct defining content for a `CredentialOffer`.
#[derive(Debug, PartialEq, Clone)]
pub enum CredentialOfferContent {
    CredDef(CredentialDefinition),
    SupportedProofs(Option<HashMap<pop::Format, Vec<crypto::Alg>>>),
}

/// A protocol-specific data for the `CredentialOffer`.
///
/// *NOTE*: will be extended in the next releases.
#[derive(Debug, PartialEq, Clone, Default)]
pub struct CredentialOfferData {}

/// A struct for handling Proof of Possession.
#[derive(Debug, PartialEq, Clone, Default)]
pub struct Proof {
    pub format: String,
    pub proof: String,
}

/// A `CredentialRequest` entity.
///
/// Contains the data related to requested `Credential`.
///
/// Built by `Holder` to be propagated later to the `Issuer` in exchange for actual `Credential`.
///
/// *NOTE*: Proof of Possession is mandatory.
#[derive(Debug, PartialEq, Clone, Default)]
pub struct CredentialRequest {
    pub cred_def_id: String,
    pub cred_offer_id: Option<String>,
    pub proof: Proof,
    pub protocol_data: Option<CredentialRequestData>, // Protocol specific
}

/// A protocol-specific data for the `CredentialRequest`.
///
/// *NOTE*: will be extended in the next releases.
#[derive(Debug, PartialEq, Clone, Default)]
pub struct CredentialRequestData {}

/// An entity used to prepare a `Presentation` for the `Verifier`.
///
/// Contains the parameters used by `Holder` to find a suitable `Credential`s.
#[derive(Debug, PartialEq, Clone)]
pub struct PresentationInput {
    pub id: String,
    pub format: String,
    pub type_: String,
    pub claims: serde_json::Map<String, serde_json::Value>,
}

/// A struct that defines how to display the claim.
///
/// *NOTE*: will be extended in the next releases.
#[derive(Debug, PartialEq, Clone)]
pub struct Display;

/// `vc:core` API Error.
///
/// Used by all `Issuer`, `Holder` and `Verifier` APIs.
#[derive(Snafu)]
#[snafu(visibility(pub(super)))]
#[non_exhaustive]
pub enum Error {
    #[snafu(display("Credential definition not found for ID: {id}"))]
    CredDefNotFound { id: String },
    #[snafu(display("Proof format required"))]
    ProofFormatRequired,
    #[snafu(display("Requested credential not found"))]
    RequestedCredentialNotFound,
    #[snafu(display("Inconsistent protocol data for format: {format}"))]
    InconsistentProtocolData { format: String },
    #[snafu(display("Unsupported format: {format}"))]
    FormatNotSupported { format: String },
    #[snafu(display("Unsupported algorithm: {alg}"))]
    AlgNotSupported { alg: String },
    #[snafu(display("Unsupported proof format: {format}"))]
    ProofFormatNotSupported { format: String },
    #[snafu(display("VC error at {location}"))]
    VC {
        #[snafu(implicit)]
        location: Location,
        source: VCError,
    },
    #[snafu(display("Metadata error at {location}"))]
    Metadata {
        #[snafu(implicit)]
        location: Location,
        source: MetadataError,
    },
    #[snafu(display("Proof error at {location}"))]
    Proof {
        #[snafu(implicit)]
        location: Location,
        source: ProofError,
    },
    #[snafu(display("KMS error at {location}"))]
    KMS {
        #[snafu(implicit)]
        location: Location,
        source: KmsError,
    },
    #[snafu(display("Proof error at {location}"))]
    Vault {
        #[snafu(implicit)]
        location: Location,
        source: VaultError,
    },
}

impl Debug for Error {
    fn fmt(&self, fmt: &mut std::fmt::Formatter) -> std::fmt::Result {
        std::write!(fmt, "{}", self)?;

        let mut error: &dyn std::error::Error = self;
        while let Some(source) = error.source() {
            write!(fmt, "\n Cause: {}", source)?;
            error = source;
        }

        Ok(())
    }
}

/// `Result` alias for vc:core API [Error].
pub type Result<T> = core::result::Result<T, Error>;

/// An async low-level protocol-agnostic `Issuer` API.
///
/// Provides the methods for creating a `CredentialOffer` and issuing a `Credential`.
///
/// # Implementation
///
/// Implementation for `Issuer`: [IssuerService](crate::vc::core::issuer::IssuerService).
#[async_trait]
pub trait Issuer: Send + Sync {
    /// Create a `CredentialOffer` based on some `CredentialDefinition`.
    ///
    ///
    /// Generated `CredentialOffer` matches provided `CredentialDefinition`
    /// and should be later used by `Holder` to create a corresponding `CredentialRequest`.
    ///
    /// # Arguments
    ///
    /// * `cred_def_id` - a `CredentialDefinition`s ID used for `CredentialOffer` creation.
    /// * `protocol_data` - (opt) protocol-specific data.
    ///
    /// # Returns
    ///
    /// A `CredentialOffer` to be shared with `Holder` on success.
    ///
    /// # Errors
    ///
    /// * [Error::CredDefNotFound] - `CredentialDefinition` not found.
    fn offer_credential(
        &self,
        cred_def_id: &str,
        protocol_data: Option<&CredentialOfferData>,
    ) -> Result<CredentialOffer>;

    /// Issue a `Credential` based on the `CredentialRequest`.
    ///
    /// `CredentialRequest` should match some existing `CredentialDefinition` of the `Issuer`.
    ///
    /// # Arguments
    ///
    /// * `credential_request` - a `CredentialRequest` used for `Credential` generation.
    /// * `claims` - claims to include into the `Credential`.
    /// * `nonce` - a nonce to validate the `Proof` included in the `CredentialRequest`.
    ///
    /// # Returns
    ///
    /// A `Credential` with its related `CredentialMetadata` in tuple on success.
    ///
    /// # Errors
    ///
    /// * [Error::CredDefNotFound] - `CredentialDefinition` not found.
    /// * [Error::FormatNotSupported] - `VC` format is not supported by the `Issuer`.
    /// * [Error::VC] - internal error [VCFormatError](crate::vc::VCFormatError).
    /// * [Error::KMS] - error with [Kms](crate::kms::Kms).
    /// * [Error::Proof] - proof is invalid.
    /// * [Error::Metadata] - fails to generate `CredentialMetadata`.
    async fn issue_credential(
        &self,
        credential_request: &CredentialRequest,
        claims: &Claims,
        nonce: &str,
    ) -> Result<(Credential, CredentialMetadata)>;
}

/// An async low-level protocol-agnostic `Holder` API.
///
/// Supports issuance and presentation flow.
///
/// # Implementation
///
/// Implementation for `Holder`: [HolderService](crate::vc::core::holder::HolderService).
#[async_trait]
pub trait Holder: Send + Sync {
    /// Prepare a `CredentialRequest`.
    ///
    /// # Arguments
    ///
    /// * `credential_offer` - a `CredentialOffer`.with definition of which `Credential` to request.
    /// * `nonce` - a nonce to generate a `ProofOfPossession`.
    ///
    /// # Returns
    ///
    /// A `CredentialRequest` to be used by `Issuer` on success.
    ///
    /// # Errors
    ///
    /// * [Error::CredDefNotFound] - `CredentialDefinition` not found.
    /// * [Error::FormatNotSupported] - cred format is not supported by the `Issuer`.
    /// * [Error::KMS] - error with [Kms](crate::kms::Kms).
    /// * [Error::Proof] - proof generations fails.
    async fn request_credential(
        &self,
        credential_offer: &CredentialOffer,
        nonce: &str,
    ) -> Result<CredentialRequest>;

    /// Store a `Credential`.
    ///
    /// This method will store the `cred` into the `Vault` under the hood.
    ///
    /// # Arguments
    ///
    /// * `credential` - a `Credential` to save.
    /// * `metadata` - the corresponding `CredentialMetadata`.
    ///
    /// # Returns
    ///
    /// An ID of the entry on success.
    ///
    /// # Errors
    ///
    /// * [Error::Vault] - error with [Vault](crate::vault::Vault).
    async fn store_credential(
        &self,
        credential: &Credential,
        metadata: &CredentialMetadata,
    ) -> Result<String>;

    /// Verify a `Credential` against an Issuer signature.
    ///
    /// This method will validate the `cred` signature.
    ///
    /// # Arguments
    ///
    /// * `credential` - a `Credential` to save.
    ///
    /// # Returns
    /// Unit type if verification succeeds.
    ///
    ///
    /// # Errors
    ///
    /// * [Error::FormatNotSupported] - VC format is not supported by the `Holder`.
    /// * [Error::VC] - internal error [VCFormatError](crate::vc::VCFormatError).
    async fn verify_credential(&self, credential: &Credential) -> Result<()>;

    /// Create a Verifiable Presentation automatically.
    ///
    /// `Holder` will automatically select first `Credential` that matched the `PresentationInput`.
    ///
    /// # Arguments
    ///
    /// * `nonce` - a nonce form `Verifier` to be used to generate `VP`.
    /// * `verifier_id` - an ID of the `Verifier`.
    /// * `presentation_input` - an input with data related to requested `VC`s.
    ///
    /// # Returns
    ///
    /// A generated `Presentation` on success.
    /// [Error::RequestedCredentialNotFound] will be raised in no suitable `Credential` was found.
    ///
    /// # Errors
    ///
    /// * [Error::FormatNotSupported] - VP format is not supported by the `Holder`.
    /// * [Error::VC] - internal error [VCFormatError](crate::vc::VCFormatError).
    /// * [Error::KMS] - error with [Kms](crate::kms::Kms).
    /// * [Error::Vault] - error with [Vault](crate::vault::Vault).
    async fn create_presentation_auto(
        &self,
        nonce: &str,
        verifier_id: &str,
        presentation_input: &PresentationInput,
    ) -> Result<Presentation>;

    /// Find the suitable `Credential`s for the provided `PresentationInput`.
    ///
    /// # Arguments
    ///
    /// * `presentation_input` - an input with data related to requested `VC`s.
    ///
    /// # Returns
    ///
    /// A Vector of `Credential` matched the provided `PresentationInput` on success.
    /// In case if nothing meets the `input` an empty Vector will be returned.
    ///
    /// # Errors
    ///
    /// * [Error::Vault] - error with [Vault](crate::vault::Vault).
    async fn find_vcs_for_presentation(
        &self,
        presentation_input: &PresentationInput,
    ) -> Result<Vec<Credential>>;

    /// Create a Verifiable Presentation.
    ///
    /// # Arguments
    ///
    /// * `nonce` - a nonce from `Verifier` to be used to generate `VP`.
    /// * `verifier_id` - an ID of the `Verifier`.
    /// * `presentation_input` - an input with the data defining the requested `VC`s.
    /// * `credential` - an actual `Credential` for the `Presentation`.
    ///
    /// # Returns
    ///
    /// A generated `Presentation` on success.
    ///
    /// # Errors
    ///
    /// * [Error::FormatNotSupported] - VP format is not supported by the `Holder`.
    /// * [Error::VC] - internal error [VCFormatError](crate::vc::VCFormatError).
    /// * [Error::KMS] - error with [Kms](crate::kms::Kms).
    /// * [Error::Vault] - error with [Vault](crate::vault::Vault).
    async fn create_presentation(
        &self,
        nonce: &str,
        verifier_id: &str,
        presentation_input: &PresentationInput,
        credential: &Credential,
    ) -> Result<Presentation>;
}

/// An async low-level protocol-agnostic `Verifier` API.
///
/// Provides basic method for verification of `VP`s.
///
/// # Implementation
///
/// Implementation for `Verifier`: [VerifierService](crate::vc::core::verifier::VerifierService).
#[async_trait]
pub trait Verifier: Send + Sync {
    /// Verify a `Presentation`.
    ///
    /// # Arguments
    ///
    /// * `nonce` - a nonce used to generate `Presentation`.
    /// * `presentation` - an `Presentation` to verify.
    ///
    /// # Returns
    ///
    /// Verified `Claims` on success.
    ///
    /// # Errors
    ///
    /// * [Error::FormatNotSupported] - VP format is not supported by the `Holder`.
    /// * [Error::VC] - internal error [VCFormatError](crate::vc::VCFormatError).
    async fn verify_presentation(&self, nonce: &str, presentation: &Presentation)
        -> Result<Claims>;
}
