use crate::http::HttpClient;
use crate::kms::Error as KmsError;
use crate::nonce::Nonce;
use crate::utils::wasm::{WasmNotSend, WasmNotSync};
use crate::vault::{CredentialEntry, Error as VaultError};
use crate::vc::VCStatus;
use crate::vc::VCStatusesData;
use crate::vc::claims::{Claim, Claims};
use crate::vc::core::DEFAULT_POP_LIFETIME_MINUTES;
use crate::vc::oid4vp::CredentialsFindResult;
use crate::vc::status_formats::StatusListFormat;
use crate::vc::{
    Credential, CredentialMetadata, Presentation, StatusList, VCFormat, formats::Error as VCError,
    pop, pop::Error as ProofError,
};
use crate::{crypto, vc};
use async_trait::async_trait;
use common_macros::DebugError;
use regex::Regex;
use serde::{Deserialize, Serialize};
use serde_json::Value;
use snafu::{Location, ResultExt, Snafu};
use std::collections::HashMap;
use std::fmt::Debug;
use time::Duration;
use url::Url;

/// A metadata for the `Issuer`.
///
/// Encapsulates all necessary data needed to handle issuance of the `Credential`s.
///
/// One `IssuerMetadata` supports multiple [CredentialDefinition]s.
#[derive(Debug, PartialEq, Clone)]
pub struct IssuerMetadata {
    pub issuer_id: String,
    pub cred_defs: Vec<CredentialDefinition>,
    pub protocol_data: Option<IssuerMetadataData>, // Protocol specific
}

/// A metadata for the `Status Issuer`
///
/// This structure encapsulates all the necessary data required to handle the issuance of status lists.
#[derive(Debug, PartialEq, Clone)]
pub struct StatusIssuerMetadata {
    pub issuer_id: String,
    pub supported_status_lists: Vec<StatusListDefinition>,
}

/// Defines a token status list associated metadata for issuance.
///
/// # Fields
///
/// - `id`: a unique identifier for the status list definition.
/// - `format`: the format of the status list
/// - `key_metadata`: the metadata of the cryptographic key that is used to sign a status list.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct StatusListDefinition {
    pub id: String,
    pub format: StatusListFormat,
    pub key_metadata: KeyMetadata,
}

/// A protocol-specific data for the `Issuer`.
///
/// *NOTE*: will be extended in the next releases.
#[derive(Debug, PartialEq, Clone)]
pub struct IssuerMetadataData {}

/// A `CredentialDefinition` for the `Issuer`.
///
/// Defines the Credential Schema and enlists the claims expected in the corresponding `Credential`.
/// Contains other various data necessary for creation of `Credential` as well.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct CredentialDefinition {
    pub cred_def_id: String,
    pub format: VCFormat,
    pub claims: HashMap<String, Display>,
    pub supported_proofs: Option<HashMap<pop::Format, Vec<crypto::Alg>>>,
    pub supported_signing_algs: Option<Vec<crypto::Alg>>,
    pub display: Option<Display>,
    pub protocol_data: Option<CredentialDefinitionData>, // Protocol specific
    pub key_metadata: KeyMetadata,
}

/// A helper struct for handling Keys and DIDs for the services.
///
/// Contains `DIDURL` of the party and the corresponding `KID` to access the key.
#[derive(Debug, PartialEq, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct KeyMetadata {
    pub did_url: String,
    pub kid: String,
}

/// A metadata for the `Holder`.
///
/// Encapsulates all necessary data needed to request a `Credential`.
#[derive(Debug, PartialEq, Clone)]
pub struct HolderMetadata {
    pub client_id: String,
    pub pop: ProofOfPossessionMetadata,
}

/// A metadata for Proof of Possession generation.
#[derive(Debug, PartialEq, Clone, Copy)]
pub struct ProofOfPossessionMetadata {
    /// Proof of possession lifetime
    pub lifetime: Duration,
    /// Proof of possession valid not before generation
    pub not_before: Option<ProofOfPossessionNotBefore>,
}

impl Default for ProofOfPossessionMetadata {
    fn default() -> Self {
        Self {
            lifetime: Duration::minutes(DEFAULT_POP_LIFETIME_MINUTES),
            not_before: None,
        }
    }
}

pub type ProofOfPossessionNotBefore = pop::ProofOfPossessionNotBefore;

/// A format-specific data for the `CredentialDefinition`.
///
/// *NOTE*: will be extended in the next releases.
#[derive(Debug, PartialEq, Clone, Serialize, Deserialize)]
#[non_exhaustive]
pub enum CredentialDefinitionData {
    SdJwt {
        vct: String,
        disclosures: Vec<String>,
        lifetime: Option<Duration>,
    },
    Ldp {
        contexts: Vec<String>,
        vc_types: Vec<String>,
        credential_id: Option<String>,
        lifetime: Option<Duration>,
    },
}

/// A `CredentialOffer` entity
///
/// Contains the data related to offered `Credential`.
///
/// Generated by `Issuer` to be used later by `Holder` to build a proper `CredentialRequest`.
///
/// *NOTE*: will be extended in the next releases.
#[derive(Debug, PartialEq, Clone)]
pub struct CredentialOffer {
    pub cred_offer_id: Option<String>,
    pub issuer_id: String,
    pub cred_def_id: String,
    pub content: CredentialOfferContent,
    pub protocol_data: Option<CredentialOfferData>, // Protocol specific
}

/// A struct defining content for a `CredentialOffer`.
#[derive(Debug, PartialEq, Clone)]
pub enum CredentialOfferContent {
    CredDef(CredentialDefinition),
    SupportedProofs(Option<HashMap<pop::Format, Vec<crypto::Alg>>>),
}

/// A protocol-specific data for the `CredentialOffer`.
///
/// *NOTE*: will be extended in the next releases.
#[derive(Debug, PartialEq, Clone, Default)]
pub struct CredentialOfferData {}

/// A struct for handling Proof of Possession.
#[derive(Debug, PartialEq, Clone, Default)]
pub struct Proof {
    pub format: String,
    pub proof: String,
}

/// A `CredentialRequest` entity.
///
/// Contains the data related to requested `Credential`.
///
/// Built by `Holder` to be propagated later to the `Issuer` in exchange for actual `Credential`.
///
/// *NOTE*: Proof of Possession is mandatory.
#[derive(Debug, PartialEq, Clone, Default)]
pub struct CredentialRequest {
    pub cred_def_id: String,
    pub cred_offer_id: Option<String>,
    pub proof: Proof,
    pub protocol_data: Option<CredentialRequestData>, // Protocol specific
}

/// An enumeration that defines the different representations for credential status information.
///
/// # Variants:
///
/// * `TokenStatusList` - Indicates that the status is managed using a token-based status list.
/// * `BitstringStatusList` - Indicates that the status is managed using a bitstring representation
#[derive(Debug, Clone)]
pub enum CredentialStatusInfo {
    TokenStatusList { idx: u32, uri: Url },
    BitstringStatusList,
}

/// A protocol-specific data for the `CredentialRequest`.
///
/// *NOTE*: will be extended in the next releases.
#[derive(Debug, PartialEq, Clone, Default)]
pub struct CredentialRequestData {
    pub proof_tolerance: Option<Duration>,
}

/// Represents a restrictions for presented credentials.
///
/// # Fields
/// - `fields`: A list of field names that must be present in the credential.
/// - `value`: An optional value that the field(s) must match.
/// - `optional`: A flag indicates whether the specified field(s) is optional.
#[derive(Debug, PartialEq, Clone)]
pub struct PresentationRestriction {
    pub fields: Vec<String>,
    pub value: Option<PresentationRestrictionValue>,
    pub optional: bool,
}

/// An entity used to prepare a `Presentation` for the `Verifier`.
///
/// Contains the parameters used by `Holder` to find a suitable `Credential`s.
#[derive(Debug, PartialEq, Clone)]
pub struct PresentationInput {
    pub id: String,
    pub format: Option<String>,
    pub restrictions: Vec<PresentationRestriction>,
}

/// A struct that defines how to display the claim.
///
/// *NOTE*: will be extended in the next releases.
#[derive(Debug, PartialEq, Clone, Serialize, Deserialize)]
pub struct Display;

/// `vc:core` API Error.
///
/// Used by all `Issuer`, `Holder` and `Verifier` APIs.
#[derive(Snafu, DebugError)]
#[snafu(visibility(pub(crate)))]
pub enum Error {
    #[snafu(display("Credential definition not found for ID: {id}"))]
    CredDefNotFound { id: String },
    #[snafu(display("Claims not found: {details}"))]
    ClaimsNotFound { details: String },
    #[snafu(display("Proof format required"))]
    ProofFormatRequired,
    #[snafu(display("Requested credential not found: {details}"))]
    RequestedCredentialNotFound { details: String },
    #[snafu(display("Inconsistent protocol data for format: {format}"))]
    InconsistentProtocolData { format: String },
    #[snafu(display("Unsupported format: {format}"))]
    FormatNotSupported { format: String },
    #[snafu(display("Unsupported algorithm: {alg}"))]
    AlgNotSupported { alg: String },
    #[snafu(display("Unsupported proof format: {format}"))]
    ProofFormatNotSupported { format: String },
    #[snafu(display("Invalid DID Url: {input}"))]
    InvalidDIDUrl { input: String },
    #[snafu(display("VC error"))]
    VC {
        #[snafu(implicit)]
        location: Location,
        source: VCError,
    },
    #[snafu(display("Proof error"))]
    Proof {
        #[snafu(implicit)]
        location: Location,
        source: ProofError,
    },
    #[snafu(display("KMS error"))]
    KMS {
        #[snafu(implicit)]
        location: Location,
        source: KmsError,
    },
    #[snafu(display("Vault error"))]
    Vault {
        #[snafu(implicit)]
        location: Location,
        source: VaultError,
    },
    #[snafu(display("Parse error"))]
    Parse {
        #[snafu(implicit)]
        location: Location,
        source: serde_json::Error,
    },

    #[snafu(display("Claims error"))]
    Claims {
        source: vc::claims::Error,
        #[snafu(implicit)]
        location: Location,
    },

    #[snafu(display("Could not parse context as Iri"))]
    ContextParsing {
        source: iref::iri::InvalidIriRef<String>,
        #[snafu(implicit)]
        location: Location,
    },

    #[snafu(display("Could not obtain VC status {details}"))]
    VCStatus {
        details: String,
        #[snafu(implicit)]
        location: Location,
    },

    #[snafu(display("status_list field not provided"))]
    StatusListNotProvided,

    #[snafu(display("Credential status not supported"))]
    CredentialStatusNotSupported,

    #[snafu(display("Credential status protocol is not supported by format: {format}"))]
    CredentialStatusProtocolNotSupported { format: String },

    #[snafu(display("Status list creating failed: {details}"))]
    StatusListCreating { details: String },

    #[snafu(display("Inconsistent status list issuance data: {details}"))]
    InconsistentStatusListData { details: String },

    #[snafu(display("Cannot create regex"))]
    CannotCreateRegex { source: regex::Error },

    #[snafu(display("Claims did not pass filtering: {details}"))]
    ClaimsDidNotPassFiltering { details: String },

    #[snafu(display("Credential is expired"))]
    CredentialExpired,

    #[snafu(display("Error during expiration check"))]
    ExpirationCheck {
        source: vc::formats::Error,
        #[snafu(implicit)]
        location: Location,
    },

    #[snafu(display("VC is not valid: {details}"))]
    VCNotValid { details: String },
}

/// `Result` alias for vc:core API [Error].
pub type Result<T> = core::result::Result<T, Error>;

/// First step of two-step VC issuance: validate the request, resolve issuer/holder
/// metadata, and build an [crate::vc::core::UnsignedCredential] ready for signing.
///
/// The caller may inspect the unsigned credential before passing it to a
/// [SignCredential] implementation.
#[cfg_attr(target_arch = "wasm32", async_trait(?Send))]
#[cfg_attr(not(target_arch = "wasm32"), async_trait)]
pub trait PrepareCredential: WasmNotSend + WasmNotSync {
    /// Validate the credential request, resolve issuer/holder metadata, and build the
    /// unsigned credential representation.
    ///
    /// # Errors
    ///
    /// Same error variants as [Issuer::issue_credential] for the validation/resolution
    /// portion of the flow.
    async fn prepare_credential(
        &self,
        credential_request: &CredentialRequest,
        claims: &Claims,
        nonce: Option<Nonce>,
        status_info: Option<CredentialStatusInfo>,
    ) -> Result<crate::vc::core::UnsignedCredential>;
}

/// Second step of two-step VC issuance: sign an [crate::vc::core::UnsignedCredential]
/// and return a finished [Credential].
///
/// The implementation is responsible for both the cryptographic operation and any
/// format-specific assembly (SD-JWT disclosures, LDP proof object).
///
/// The trait is intentionally monolithic: a single method accepts the
/// `UnsignedCredential` enum and dispatches internally. Implementations specialised to
/// one format MUST return [Error::FormatNotSupported] for the other variant.
#[cfg_attr(target_arch = "wasm32", async_trait(?Send))]
#[cfg_attr(not(target_arch = "wasm32"), async_trait)]
pub trait SignCredential: WasmNotSend + WasmNotSync {
    /// Sign the unsigned credential.
    ///
    /// # Errors
    ///
    /// * [Error::FormatNotSupported] - the implementation does not support the
    ///   credential's format.
    /// * [Error::KMS] - the implementation could not locate the requested key.
    /// * [Error::VC] - format-specific signing error.
    async fn sign_credential(
        &self,
        unsigned_credential: crate::vc::core::UnsignedCredential,
    ) -> Result<Credential>;
}

/// An async low-level protocol-agnostic `Issuer` API.
///
/// Provides the methods for creating a `CredentialOffer` and issuing a `Credential`.
///
/// # Implementation
///
/// Implementation for `Issuer`: [IssuerService](crate::vc::core::issuer::IssuerService).
#[cfg_attr(target_arch = "wasm32", async_trait(?Send))]
#[cfg_attr(not(target_arch = "wasm32"), async_trait)]
pub trait Issuer: WasmNotSend + WasmNotSync {
    /// Create a `CredentialOffer` based on some `CredentialDefinition`.
    ///
    ///
    /// Generated `CredentialOffer` matches provided `CredentialDefinition`
    /// and should be later used by `Holder` to create a corresponding `CredentialRequest`.
    ///
    /// # Arguments
    ///
    /// * `cred_def_id` - a `CredentialDefinition`s ID used for `CredentialOffer` creation.
    /// * `protocol_data` - (opt) protocol-specific data.
    ///
    /// # Returns
    ///
    /// A `CredentialOffer` to be shared with `Holder` on success.
    ///
    /// # Errors
    ///
    /// * [Error::CredDefNotFound] - `CredentialDefinition` not found.
    fn offer_credential(
        &self,
        cred_def_id: &str,
        protocol_data: Option<&CredentialOfferData>,
    ) -> Result<CredentialOffer>;

    /// Issue a `Credential` based on the `CredentialRequest`.
    ///
    /// `CredentialRequest` should match some existing `CredentialDefinition` of the `Issuer`.
    ///
    /// # Arguments
    ///
    /// * `credential_request` - a `CredentialRequest` used for `Credential` generation.
    /// * `claims` - claims to include into the `Credential`.
    /// * `nonce` - an optional nonce to validate the `Proof` included in the `CredentialRequest`.
    ///
    /// # Returns
    ///
    /// An issued `Credential` on success.
    ///
    /// # Errors
    ///
    /// * [Error::CredDefNotFound] - `CredentialDefinition` not found.
    /// * [Error::FormatNotSupported] - `VC` format is not supported by the `Issuer`.
    /// * [Error::VC] - internal error [VCFormatError](crate::vc::VCFormatError).
    /// * [Error::KMS] - error with [Kms](crate::kms::Kms).
    /// * [Error::Proof] - proof is invalid.
    async fn issue_credential(
        &self,
        credential_request: &CredentialRequest,
        claims: &Claims,
        nonce: Option<Nonce>,
        status_info: Option<CredentialStatusInfo>, // TODO: consider moving it to CredentialRequest
    ) -> Result<Credential>;
}

/// Status lists Issuer.
///
/// Provides method for issuing VC status lists
#[cfg_attr(target_arch = "wasm32", async_trait(?Send))]
#[cfg_attr(not(target_arch = "wasm32"), async_trait)]
pub trait StatusIssuer: WasmNotSend + WasmNotSync {
    /// Issues a new status list for a given status list identifier and a set of credential statuses.
    ///
    /// # Arguments
    ///
    /// * `status_list_id` - a unique identifier of the status list definition.
    /// * `statuses` - credential statuses data.
    ///
    /// # Returns
    ///
    ///  The issued `StatusList` if successful.
    ///
    /// # Errors
    ///
    /// * [Error] an error if the issuance process fails.
    async fn issue_status_list(
        &self,
        status_list_id: &str,
        statuses: VCStatusesData,
    ) -> Result<StatusList>;
}

/// An async low-level protocol-agnostic `Holder` API.
///
/// Supports issuance and presentation flow.
///
/// # Implementation
///
/// Implementation for `Holder`: [HolderService](crate::vc::core::holder::HolderService).
#[cfg_attr(target_arch = "wasm32", async_trait(?Send))]
#[cfg_attr(not(target_arch = "wasm32"), async_trait)]
pub trait Holder: WasmNotSend + WasmNotSync {
    /// Prepare a `CredentialRequest`.
    ///
    /// # Arguments
    ///
    /// * `credential_offer` - a `CredentialOffer`.with definition of which `Credential` to request.
    /// * `nonce` - optional nonce to generate a `ProofOfPossession`.
    /// * `key_metadata` - a `KeyMetadata` for corresponding key to be used for signing operations.
    ///
    /// # Returns
    ///
    /// A `CredentialRequest` to be used by `Issuer` on success.
    ///
    /// # Errors
    ///
    /// * [Error::CredDefNotFound] - `CredentialDefinition` not found.
    /// * [Error::FormatNotSupported] - cred format is not supported by the `Issuer`.
    /// * [Error::KMS] - error with [Kms](crate::kms::Kms).
    /// * [Error::Proof] - proof generations fails.
    async fn request_credential(
        &self,
        credential_offer: &CredentialOffer,
        nonce: Option<Nonce>,
        key_metadata: &KeyMetadata,
    ) -> Result<CredentialRequest>;

    /// Store a `Credential`.
    ///
    /// This method will store the `cred` into the `Vault` under the hood.
    ///
    /// # Arguments
    ///
    /// * `credential` - a `Credential` to save.
    /// * `metadata` - the corresponding `CredentialMetadata`.
    ///
    /// # Returns
    ///
    /// An ID of the entry on success.
    ///
    /// # Errors
    ///
    /// * [Error::Vault] - error with [Vault](crate::vault::Vault).
    async fn store_credential(
        &self,
        credential: &Credential,
        metadata: &CredentialMetadata,
    ) -> Result<String>;

    /// Verify a `Credential` against an Issuer signature.
    ///
    /// This method will validate the `cred` signature.
    ///
    /// # Arguments
    ///
    /// * `credential` - a `Credential` to save.
    ///
    /// # Returns
    /// Unit type if verification succeeds.
    ///
    ///
    /// # Errors
    ///
    /// * [Error::FormatNotSupported] - VC format is not supported by the `Holder`.
    /// * [Error::VC] - internal error [VCFormatError](crate::vc::VCFormatError).
    async fn verify_credential(&self, credential: &Credential) -> Result<()>;

    /// Create a Verifiable Presentation automatically.
    ///
    /// `Holder` will automatically select first `Credential` that matched the `PresentationInput`.
    ///
    /// # Arguments
    ///
    /// * `holder_binding` - whether to bind holder in the credential or not. It can be NotRequired or Required with nonce and verifier_id
    /// * `presentation_input` - an input with data related to requested `VC`s.
    ///
    /// # Returns
    ///
    /// A generated `Presentation` on success.
    /// [Error::RequestedCredentialNotFound] will be raised in no suitable `Credential` was found.
    ///
    /// # Errors
    ///
    /// * [Error::FormatNotSupported] - VP format is not supported by the `Holder`.
    /// * [Error::VC] - internal error [VCFormatError](crate::vc::VCFormatError).
    /// * [Error::KMS] - error with [Kms](crate::kms::Kms).
    /// * [Error::Vault] - error with [Vault](crate::vault::Vault).
    async fn create_presentation_auto(
        &self,
        holder_binder: Option<HolderBinder>,
        presentation_input: &PresentationInput,
    ) -> Result<Presentation>;

    /// Find the suitable `CredentialEntry`s for the provided `PresentationInput`.
    ///
    /// # Arguments
    ///
    /// * `presentation_input` - an input with data related to requested `VC`s.
    ///
    /// # Returns
    ///
    /// A Vector of `CredentialEntry` matched the provided `PresentationInput` on success.
    /// In case if nothing meets the `input` an empty Vector will be returned.
    ///
    /// # Errors
    ///
    /// * [Error::Vault] - error with [Vault](crate::vault::Vault).
    async fn find_vcs_for_presentation(
        &self,
        presentation_input: &PresentationInput,
    ) -> Result<CredentialsFindResult>;

    /// Create a Verifiable Presentation.
    ///
    /// # Arguments
    ///
    /// * `holder_binder` - whether to bind holder in the credential or not. It should have nonce and verifier_id if given
    /// * `presentation_input` - an input with the data defining the requested `VC`s.
    /// * `credential` - an actual `CredentialEntry` for the `Presentation`.
    ///
    /// # Returns
    ///
    /// A generated `Presentation` on success.
    ///
    /// # Errors
    ///
    /// * [Error::FormatNotSupported] - VP format is not supported by the `Holder`.
    /// * [Error::VC] - internal error [VCFormatError](crate::vc::VCFormatError).
    /// * [Error::KMS] - error with [Kms](crate::kms::Kms).
    /// * [Error::Vault] - error with [Vault](crate::vault::Vault).
    async fn create_presentation(
        &self,
        holder_binder: Option<HolderBinder>,
        presentation_input: &PresentationInput,
        credential: &CredentialEntry,
    ) -> Result<Presentation>;

    /// Produce a delegated credential (dSD-JWT) from a selected SD-JWT credential entry,
    /// appending one delegation link via the format layer. Mirrors `create_presentation`
    /// but emits a stored-credential dSD-JWT rather than a verifiable presentation.
    ///
    /// # Arguments
    ///
    /// * `cred_entry` - a `CredentialEntry` whose `credential` must be an SD-JWT.
    /// * `params` - delegation hop parameters (delegate payload, claims to disclose, binding mode).
    ///
    /// # Returns
    ///
    /// A compact dSD-JWT string ending with `~` (a grant, not a KB-JWT presentation) on success.
    ///
    /// # Errors
    ///
    /// * [Error::FormatNotSupported] - the credential is not an SD-JWT (delegation is only supported for SD-JWT).
    /// * [Error::VC] - internal format-layer error.
    /// * [Error::KMS] - error with [Kms](crate::kms::Kms).
    #[cfg(feature = "delegate-sd-jwt")]
    async fn create_delegated_credential(
        &self,
        cred_entry: &CredentialEntry,
        params: vc::formats::DelegationParams,
    ) -> Result<vc::formats::sd_jwt_vc::Credential>;

    /// Gets the status of Credential.
    ///
    /// # Arguments
    ///
    /// * `credential` - a [Credential] containing the status claim.
    ///
    /// # Returns
    ///
    /// [VCStatus] on success
    ///
    /// # Errors
    ///
    /// * [Error::CredentialStatusNotSupported] - Getting VC status is not supported for the given VC format.
    /// * [Error::VCStatus] - Error getting VC status.
    async fn get_credential_status(&self, credential: &Credential) -> Result<Option<VCStatus>>;
}

/// An async low-level protocol-agnostic `Verifier` API.
///
/// Provides basic method for verification of `VP`s.
///
/// # Implementation
///
/// Implementation for `Verifier`: [VerifierService](crate::vc::core::verifier::VerifierService).
#[cfg_attr(target_arch = "wasm32", async_trait(?Send))]
#[cfg_attr(not(target_arch = "wasm32"), async_trait)]
pub trait Verifier: WasmNotSend + WasmNotSync {
    /// Verify a `Presentation`.
    ///
    /// # Arguments
    ///
    /// * `holder_binder` - if given: a nonce and verifier_id used to generate `Presentation` with binding the holder.
    /// * `presentation` - a `Presentation` to verify.
    ///
    /// # Returns
    ///
    /// Verified `Claims` on success.
    ///
    /// # Errors
    ///
    /// * [Error::FormatNotSupported] - VP format is not supported by the `Holder`.
    /// * [Error::VC] - internal error [VCFormatError](vc::VCFormatError).
    async fn verify_presentation(
        &self,
        holder_binder: Option<HolderBinder>,
        presentation: &Presentation,
        http_client: &dyn HttpClient,
    ) -> Result<Claims>;

    /// Obtains the status for presented VC.
    ///
    /// # Arguments
    ///
    /// * `presentation` - a `Presentation` containing VC data.
    /// * `http_client` - a http client.
    ///
    /// # Returns
    ///
    /// VC Status on success
    ///
    /// # Errors
    ///
    /// * [Error] an error if the obtaining process fails.
    async fn obtain_credential_status(
        &self,
        presentation: &Presentation,
        http_client: &dyn HttpClient, // TODO: is it ok to use `dyn`?
    ) -> Result<Option<VCStatus>>;
}

type SetOfValues = Vec<String>;

#[derive(Debug, PartialEq, Clone)]
pub enum PresentationRestrictionValue {
    Const(String),
    Pattern(String),
    //special case for type_values: Check if at least one of inner array(all of its strings) exist
    ArrayOfValues(Vec<SetOfValues>),
}

impl PresentationRestrictionValue {
    pub fn validate_claim_for_string_or_pattern(&self, value: Value) -> Result<bool> {
        let binding = value.to_string();
        let claim = binding.trim_matches('\"').trim();

        let result = match &self {
            PresentationRestrictionValue::Pattern(pattern) => Regex::new(pattern)
                .context(CannotCreateRegexSnafu)?
                .is_match(claim),
            PresentationRestrictionValue::Const(string) => claim.cmp(string).is_eq(),
            PresentationRestrictionValue::ArrayOfValues(type_value_sets) => {
                unreachable!()
            }
        };
        Ok(result)
    }

    pub fn validate_claims_for_existence_as_sets(
        &self,
        values: Vec<Value>,
        type_value_sets: &Vec<SetOfValues>,
    ) -> bool {
        let mut val_strs = vec![];
        for val in values {
            if let Value::String(val_str) = val {
                val_strs.push(val_str.to_owned());
            }
        }
        for type_value_set in type_value_sets {
            if self.all_exist(type_value_set, &val_strs) {
                return true;
            }
        }
        false
    }

    fn all_exist(&self, type_value_set: &SetOfValues, vals: &[String]) -> bool {
        for type_value in type_value_set {
            if !vals.contains(type_value) {
                return false;
            }
        }
        true
    }
    pub fn get_type(&self) -> String {
        match &self {
            PresentationRestrictionValue::Const(_) => "const".to_string(),
            PresentationRestrictionValue::Pattern(_) => "pattern".to_string(),
            PresentationRestrictionValue::ArrayOfValues(_) => {
                "array_of_array_of_strings".to_string()
            }
        }
    }
    pub fn get_value(&self) -> Claim {
        match &self {
            PresentationRestrictionValue::Const(value) => Claim::String(value.to_owned()),
            PresentationRestrictionValue::Pattern(value) => Claim::String(value.to_owned()),
            PresentationRestrictionValue::ArrayOfValues(values) => Claim::Array(
                values
                    .iter()
                    .map(|set| {
                        Claim::Array(set.iter().map(|v| Claim::String(v.to_owned())).collect())
                    })
                    .collect(),
            ),
        }
    }
}

#[derive(Debug, PartialEq, Clone)]
pub struct HolderBinder {
    pub nonce: Nonce,
    pub verifier_id: String,
    pub response_uri: Option<String>,
}
