use async_trait::async_trait;
use snafu::{Location, Snafu};
use std::collections::HashMap;
use std::fmt::Debug;

use crate::kms::Error as KmsError;
use crate::vault::Error as VaultError;
use crate::vc::{
    formats::Error as VCError, pop::Error as ProofError, metadata::Error as MetadataError,
    Claims, Credential, CredentialMetadata, Presentation, VCFormat
};

mod verifier;
mod holder;
mod issuer;

pub use holder::HolderService;
pub use issuer::IssuerService;
pub use verifier::VerifierService;

//  --------- DATA MODEL -------------

/// A metadata for the `Issuer`.
///
/// Encapsulates all necessary data needed to handle issuance of the `Credential`s.
///
/// One `IssuerMetadata` supports multiple [CredentialDefinition]s.
#[derive(Debug, PartialEq, Clone)]
pub struct IssuerMetadata {
    pub issuer_id: String,
    pub cred_defs: Vec<CredentialDefinition>,
    pub protocol_data: Option<IssuerMetadataData>, // Protocol specific
    pub key_metadata: KeyMetadata,
}

/// A protocol-specific data for the `Issuer`.
///
/// *NOTE*: will be extended in the next releases.
#[derive(Debug, PartialEq, Clone)]
pub struct IssuerMetadataData {}

/// A `CredentialDefinition` for the `Issuer`.
///
/// Defines the Credential Schema and enlists the claims expected in the corresponding `Credential`.
/// Contains other various data necessary for creation of `Credential` as well.
///
/// *NOTE*: `KeyMetadata` for a `CredDef` is optional.
/// If it is `None` `Issuer`s will fall back to the root-level one.
#[derive(Debug, Clone, PartialEq)]
pub struct CredentialDefinition {
    pub cred_def_id: String,
    pub format: VCFormat,
    pub claims: HashMap<String, Display>,
    pub supported_proofs: Vec<String>,
    pub display: Option<Display>,
    pub protocol_data: Option<CredentialDefinitionData>, // Protocol specific
    pub key_metadata: Option<KeyMetadata>,
}

/// A helper struct for handling Keys and DIDs for the services.
///
/// Contains `DIDURL` of the party and the corresponding `KID` to access the key.
#[derive(Debug, PartialEq, Clone)]
pub struct KeyMetadata {
    pub did_url: String,
    pub kid: String,
}

/// A metadata for the `Holder`.
///
/// Encapsulates all necessary data needed to issue a `Credential`.
///
/// One `IssuerMetadata` supports multiple [CredentialDefinition]s.
#[derive(Debug, PartialEq, Clone)]
pub struct HolderMetadata {
    pub client_id: String,
    pub key_metadata: KeyMetadata,
}

/// A protocol-specific data for the `CredentialDefinition`.
///
/// *NOTE*: will be extended in the next releases.
#[derive(Debug, PartialEq, Clone, Default)]
pub struct CredentialDefinitionData {
    pub disclosures: Vec<String>,
    pub lifetime: Option<time::Duration>,
}

/// A `CredentialOffer` entity.
///
/// Contains the data related to offered `Credential`.
///
/// Generated by `Issuer` to be used later by `Holder` to build a proper `CredentialRequest`.
///
/// *NOTE*: will be extended in the next releases.
#[derive(Debug, PartialEq, Clone)]
pub struct CredentialOffer {
    pub issuer_id: String,
    pub cred_offer_id: Option<String>,
    pub cred_def_id: Option<String>,
    pub supported_proofs: Option<Vec<String>>,
    pub cred_def: Option<CredentialDefinition>,
    pub protocol_data: Option<CredentialOfferData>, // Protocol specific
}

/// A protocol-specific data for the `CredentialOffer`.
///
/// *NOTE*: will be extended in the next releases.
#[derive(Debug, PartialEq, Clone, Default)]
pub struct CredentialOfferData {}

/// A struct for handling Proof of Possession.
#[derive(Debug, PartialEq, Clone, Default)]
pub struct Proof {
    pub format: String,
    pub proof: String,
}

/// A `CredentialRequest` entity.
///
/// Contains the data related to requested `Credential`.
///
/// Built by `Holder` to be propagated later to the `Issuer` in exchange for actual `Credential`.
///
/// *NOTE*: Proof of Possession is mandatory.
#[derive(Debug, PartialEq, Clone, Default)]
pub struct CredentialRequest {
    pub cred_def_id: String,
    pub cred_offer_id: Option<String>,
    pub proof: Proof,
    pub protocol_data: Option<CredentialRequestData>, // Protocol specific
}

/// A protocol-specific data for the `CredentialRequest`.
///
/// *NOTE*: will be extended in the next releases.
#[derive(Debug, PartialEq, Clone, Default)]
pub struct CredentialRequestData {}

/// An entity used to prepare a `Presentation` for the `Verifier`.
///
/// Contains the parameters used by `Holder` to find a suitable `Credential`s.
#[derive(Debug, PartialEq, Clone)]
pub struct PresentationInput {
    pub id: String,
    pub format: String,
    pub type_: String,
    pub claims: serde_json::Map<String, serde_json::Value>,
}

/// A struct that defines how to display the claim.
///
/// *NOTE*: will be extended in the next releases.
#[derive(Debug, PartialEq, Clone)]
pub struct Display;

/// `vc:core` API Error.
///
/// Used by all `Issuer`, `Holder` and `Verifier` APIs.
#[derive(Snafu)]
#[non_exhaustive]
pub enum Error {
    #[snafu(display("Credential definition not found for ID: {id}"))]
    CredDefNotFound { id: String },
    #[snafu(display("Credential definition required"))]
    CredDefRequired,
    #[snafu(display("Proof format required"))]
    ProofFormatRequired,
    #[snafu(display("Requested credential not found"))]
    RequestedCredentialNotFound,
    #[snafu(display("Unsupported format: {format}"))]
    FormatNotSupported { format: String },
    #[snafu(display("VC error at {location}"))]
    VC {
        #[snafu(implicit)]
        location: Location,
        source: VCError,
    },
    #[snafu(display("Metadata error at {location}"))]
    Metadata {
        #[snafu(implicit)]
        location: Location,
        source: MetadataError,
    },
    #[snafu(display("Proof error at {location}"))]
    Proof {
        #[snafu(implicit)]
        location: Location,
        source: ProofError,
    },
    #[snafu(display("KMS error at {location}"))]
    KMS {
        #[snafu(implicit)]
        location: Location,
        source: KmsError,
    },
    #[snafu(display("Proof error at {location}"))]
    Vault {
        #[snafu(implicit)]
        location: Location,
        source: VaultError,
    },
}

impl Debug for Error {
    fn fmt(&self, fmt: &mut std::fmt::Formatter) -> std::fmt::Result {
        std::write!(fmt, "{}", self)?;

        let mut error: &dyn std::error::Error = self;
        while let Some(source) = error.source() {
            write!(fmt, "\n Cause: {}", source)?;
            error = source;
        }

        Ok(())
    }
}

/// `Result` alias for vc:core API [Error].
pub type Result<T> = core::result::Result<T, Error>;

/// An async low-level `Issuer` API.
///
/// Provides the methods for creating a `CredentialOffer` and issuing a `Credential`.
///
/// # Implementation
///
/// Implementation for `Issuer`: [IssuerService].
#[async_trait]
pub trait Issuer: Send + Sync
{
    /// Create a `CredentialOffer` based on some `CredentialDefinition`.
    ///
    ///
    /// Generated `CredentialOffer` matches provided `CredentialDefinition`
    /// and should be later used by `Holder` to create a corresponding `CredentialRequest`.
    ///
    /// # Arguments
    ///
    /// * `cred_def_id` - a `CredentialDefinition`s ID used for `CredentialOffer` creation.
    /// * `protocol_data` - (opt) protocol-specific data.
    ///
    /// # Returns
    ///
    /// A `CredentialOffer` to be shared with `Holder` on success.
    ///
    /// # Errors
    ///
    /// * [Error::CredDefNotFound] - `CredentialDefinition` not found.
    fn offer_credential(
        &self,
        cred_def_id: &str,
        protocol_data: Option<&CredentialOfferData>,
    ) -> Result<CredentialOffer>;

    /// Issue a `Credential` based on the `CredentialRequest`.
    ///
    /// `CredentialRequest` should match some existing `CredentialDefinition` of the `Issuer`.
    ///
    /// # Arguments
    ///
    /// * `credential_request` - a `CredentialRequest` used for `Credential` generation.
    /// * `claims` - claims to include into the `Credential`.
    /// * `nonce` - a nonce to validate the `Proof` included in the `CredentialRequest`.
    ///
    /// # Returns
    ///
    /// A `Credential` with its related `CredentialMetadata` in tuple on success.
    ///
    /// # Errors
    ///
    /// * [Error::CredDefNotFound] - `CredentialDefinition` not found.
    /// * [Error::FormatNotSupported] - `VC` format is not supported by the `Issuer`.
    /// * [Error::VC] - internal error [VCFormatError](crate::vc::VCFormatError).
    /// * [Error::KMS] - error with [Kms](crate::kms::Kms).
    /// * [Error::Proof] - proof is invalid.
    /// * [Error::Metadata] - fails to generate `CredentialMetadata`.
    async fn issue_credential(
        &self,
        credential_request: &CredentialRequest,
        claims: &Claims,
        nonce: &str,
    ) -> Result<(Credential, CredentialMetadata)>;
}

/// An async low-level `Holder` API.
///
/// Supports issuance and presentation flow.
///
/// # Implementation
///
/// Implementation for `Holder`: [HolderService].
#[async_trait]
pub trait Holder: Send + Sync
{
    /// Prepare a `CredentialRequest`.
    ///
    /// # Arguments
    ///
    /// * `credential_offer` - a `CredentialOffer`.with definition of which `Credential` to request.
    /// * `nonce` - a nonce to generate a `ProofOfPossession`.
    ///
    /// # Returns
    ///
    /// A `CredentialRequest` to be used by `Issuer` on success.
    ///
    /// # Errors
    ///
    /// * [Error::CredDefNotFound] - `CredentialDefinition` not found.
    /// * [Error::FormatNotSupported] - cred format is not supported by the `Issuer`.
    /// * [Error::KMS] - error with [Kms](crate::kms::Kms).
    /// * [Error::Proof] - proof generations fails.
    async fn request_credential(
        &self,
        credential_offer: &CredentialOffer,
        nonce: &str,
    ) -> Result<CredentialRequest>;

    /// Store a `Credential`.
    ///
    /// This method will store the `cred` into the `Vault` under the hood.
    ///
    /// # Arguments
    ///
    /// * `credential` - a `Credential` to save.
    /// * `metadata` - the corresponding `CredentialMetadata`.
    ///
    /// # Returns
    ///
    /// An ID of the entry on success.
    ///
    /// # Errors
    ///
    /// * [Error::Vault] - error with [Vault](crate::vault::Vault).
    async fn store_credential(
        &self,
        credential: &Credential,
        metadata: &CredentialMetadata,
    ) -> Result<String>;

    /// Verify a `Credential` against an Issuer signature.
    ///
    /// This method will validate the `cred` signature.
    ///
    /// # Arguments
    ///
    /// * `credential` - a `Credential` to save.
    ///
    /// # Returns
    /// Unit type if verification succeeds.
    ///
    ///
    /// # Errors
    ///
    /// * [Error::FormatNotSupported] - VC format is not supported by the `Holder`.
    /// * [Error::VC] - internal error [VCFormatError](crate::vc::VCFormatError).
    async fn verify_credential(
        &self,
        credential: &Credential,
    ) -> Result<()>;


    /// Create a Verifiable Presentation automatically.
    ///
    /// `Holder` will automatically select first `Credential` that matched the `PresentationInput`.
    ///
    /// # Arguments
    ///
    /// * `nonce` - a nonce form `Verifier` to be used to generate `VP`.
    /// * `verifier_id` - an ID of the `Verifier`.
    /// * `presentation_input` - an input with data related to requested `VC`s.
    ///
    /// # Returns
    ///
    /// A generated `Presentation` on success.
    /// [Error::RequestedCredentialNotFound] will be raised in no suitable `Credential` was found.
    ///
    /// # Errors
    ///
    /// * [Error::FormatNotSupported] - VP format is not supported by the `Holder`.
    /// * [Error::VC] - internal error [VCFormatError](crate::vc::VCFormatError).
    /// * [Error::KMS] - error with [Kms](crate::kms::Kms).
    /// * [Error::Vault] - error with [Vault](crate::vault::Vault).
    async fn create_presentation_auto(
        &self,
        nonce: &str,
        verifier_id: &str,
        presentation_input: &PresentationInput,
    ) -> Result<Presentation>;

    /// Find the suitable `Credential`s for the provided `PresentationInput`.
    ///
    /// # Arguments
    ///
    /// * `presentation_input` - an input with data related to requested `VC`s.
    ///
    /// # Returns
    ///
    /// A Vector of `Credential` matched the provided `PresentationInput` on success.
    /// In case if nothing meets the `input` an empty Vector will be returned.
    ///
    /// # Errors
    ///
    /// * [Error::Vault] - error with [Vault](crate::vault::Vault).
    async fn find_vcs_for_presentation(
        &self,
        presentation_input: &PresentationInput,
    ) -> Result<Vec<Credential>>;

    /// Create a Verifiable Presentation.
    ///
    /// # Arguments
    ///
    /// * `nonce` - a nonce from `Verifier` to be used to generate `VP`.
    /// * `verifier_id` - an ID of the `Verifier`.
    /// * `presentation_input` - an input with the data defining the requested `VC`s.
    /// * `credential` - an actual `Credential` for the `Presentation`.
    ///
    /// # Returns
    ///
    /// A generated `Presentation` on success.
    ///
    /// # Errors
    ///
    /// * [Error::FormatNotSupported] - VP format is not supported by the `Holder`.
    /// * [Error::VC] - internal error [VCFormatError](crate::vc::VCFormatError).
    /// * [Error::KMS] - error with [Kms](crate::kms::Kms).
    /// * [Error::Vault] - error with [Vault](crate::vault::Vault).
    async fn create_presentation(
        &self,
        nonce: &str,
        verifier_id: &str,
        presentation_input: &PresentationInput,
        credential: &Credential,
    ) -> Result<Presentation>;
}

/// An async low-level `Verifier` API.
///
/// Provides basic method for verification of `VP`s.
///
/// # Implementation
///
/// Implementation for `Verifier`: [VerifierService].
#[async_trait]
pub trait Verifier: Send + Sync
{
    /// Verify a `Presentation`.
    ///
    /// # Arguments
    ///
    /// * `nonce` - a nonce used to generate `Presentation`.
    /// * `presentation` - an `Presentation` to verify.
    ///
    /// # Returns
    ///
    /// Verified `Claims` on success.
    ///
    /// # Errors
    ///
    /// * [Error::FormatNotSupported] - VP format is not supported by the `Holder`.
    /// * [Error::VC] - internal error [VCFormatError](crate::vc::VCFormatError).
    async fn verify_presentation(
        &self,
        nonce: &str,
        presentation: &Presentation,
    ) -> Result<Claims>;
}

#[cfg(test)]
mod tests {
    use std::str::FromStr;

    use oid4vci::openidconnect::Nonce;
    use serde_json::json;
    use ssi::did::DIDURL;

    use crate::crypto::Key;
    use crate::did::didkey::DIDKey;
    use crate::inmem::kms::LocalKms;
    use crate::inmem::vault::InMemVault;
    use crate::kms::Kms;
    use crate::vc::core::holder::HolderService;
    use crate::vc::core::issuer::IssuerService;
    use crate::vc::core::verifier::VerifierService;
    use crate::vc::core::{CredentialDefinition, CredentialDefinitionData, Holder, HolderMetadata, Issuer, IssuerMetadata, KeyMetadata, PresentationInput, Verifier};
    use crate::{kms, vc};

    #[tokio::test]
    async fn e2e() {
        // Initialization
        let issuer = issuer().await;
        let holder = holder().await;
        let verifier = verifier("ver-id");

        println!("Issue credential...");

        let offer = issuer.offer_credential(
            "SD_JWT_cred",
            None,
        );
        assert!(offer.is_ok());
        let offer = offer.unwrap();

        let nonce = Nonce::new_random();
        let request = holder.request_credential(&offer, nonce.secret()).await;
        assert!(request.is_ok());
        let request = request.unwrap();

        let claims = json!( {
                "vct": "https://credentials.example.com/identity_credential",
                "given_name": "John",
                "family_name": "Doe",
                "dob": "09/09/1989",
            });
        let cl = claims.as_object().unwrap().clone();
        println!("Claims: {:?}", cl);

        let vc_res = issuer.issue_credential(&request, &claims, nonce.secret()).await;
        assert!(vc_res.is_ok());

        let (vc, vc_meta) = vc_res.unwrap();
        println!("Credential {:?}", &vc);

        let store_res = holder.store_credential(&vc, &vc_meta).await;
        assert!(store_res.is_ok());

        println!("Present proof...");

        let presentation_input = PresentationInput {
            id: "SD_JWT_cred".into(),
            type_: "https://credentials.example.com/identity_credential".to_string(),
            format: "vc+sd-jwt".into(),
            claims: json!({
               "given_name": true,
               "family_name": true,
            }).as_object().unwrap().to_owned(),
        };

        let nonce = Nonce::new_random();

        let vp_res = holder.create_presentation_auto(
            nonce.secret(), "ver-id",
            &presentation_input,
        ).await;
        assert!(vp_res.is_ok());

        let vp = vp_res.unwrap();
        println!("Presentation {:?}", vp);

        let ver_res = verifier.verify_presentation(
            nonce.secret(),
            &vp,
        ).await;
        assert!(ver_res.is_ok());

        let res_claims = ver_res.unwrap();
        println!("Presentation claims {:?}", res_claims);

        assert!(res_claims.as_object().unwrap().contains_key("given_name"));
        assert!(res_claims.as_object().unwrap().contains_key("family_name"));
        // should return not only requested claims, but all in credential
        assert!(res_claims.as_object().unwrap().contains_key("dob"));
    }

    async fn issuer() -> impl Issuer {
        // Initialization
        println!("Issuer creating...");

        let kms = LocalKms::new();
        let didkey = DIDKey::new();

        let kt = kms::KeyType::P256;
        let (kid, kh) = kms.create_and_handle(kt, kms::CreateOptions {}).await.unwrap();

        let did = didkey.generate(kh.clone()).unwrap();
        let did_url = DIDURL::from_str(&did).unwrap();
        println!("DID: {}", did);

        let jwk = kh.clone().jwk().unwrap();
        println!("Key JWK:\n{}", serde_json::to_string_pretty(&jwk).unwrap());

        let metadata = IssuerMetadata {
            issuer_id: did_url.to_string(),
            cred_defs: vec![
                CredentialDefinition {
                    cred_def_id: "SD_JWT_cred".into(),
                    format: vc::VCFormat::SdJwtVc,
                    claims: Default::default(),
                    supported_proofs: vec![
                        "jwt".into()
                    ],
                    display: None,
                    protocol_data: Some(CredentialDefinitionData {
                        disclosures: vec!["$.given_name".to_owned(), "$.family_name".to_owned()],
                        lifetime: None,
                    }),
                    key_metadata: None,
                }
            ],
            protocol_data: None,
            key_metadata: KeyMetadata {
                did_url: did_url.to_string(),
                kid: kid.clone(),
            },
        };

        IssuerService::new(kms, metadata)
    }

    async fn holder() -> impl Holder {
        // Initialization
        println!("Holder creating...");

        let kms = LocalKms::new();
        let didkey = DIDKey::new();
        let vault = InMemVault::new();

        let kt = kms::KeyType::P256;
        let (kid, kh) = kms.create_and_handle(kt, kms::CreateOptions {}).await.unwrap();

        let did = didkey.generate(kh.clone()).unwrap();
        let did_url = DIDURL::from_str(&did).unwrap();
        println!("DID: {}", did);

        let jwk = kh.clone().jwk().unwrap();
        println!("Key JWK:\n{}", serde_json::to_string_pretty(&jwk).unwrap());

        HolderService::new(kms, vault, HolderMetadata {
            client_id: "client_id".into(),
            key_metadata: KeyMetadata {
                did_url: did_url.to_string(),
                kid: kid.clone(),
            },
        })
    }

    fn verifier(id: &str) -> impl Verifier {
        VerifierService::new(id)
    }
}