[package]
name = "multi-thread"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.8.0"
actix-web-httpauth = "0.8.2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tracing-subscriber = "0.3.18"
tokio = { version = "1.40.0", features = ["macros", "rt-multi-thread"] }
futures = "0.3.30"
rand = "0.9.1"

agent-sdk = { path = "../..", features = ["in-memory"] }
