@startuml
'https://plantuml.com/component-diagram
'left to right direction

package "Applications" as App #LightBlue {
    package "Mobile App (Holder)" as MAPP {
        [KMS Impl] as KMSM
        [Vault Impl] as VaultM
        [App Logic] as AppM
    }

    cloud "Web App (Issuer, Verifier)" {
        [Web App Endpoints] as AppW
        [KMS Impl] as KMSW
        [Vault Impl] as VaultW
    }
}

package "ASDK" as ASDK #LightGray {

    package VC {

        package Core as VCCore {
            [Issuer API] as CoreI  #Green
            [Holder API] as CoreH #Green
            [Verifier API] as CoreV #Green
        }

        package OID4VC as VCOID {
            [Issuer API] as OIDI #Green
            [Holder API] as OIDH #Green
            [Verifier API] as OIDV #Green
        }

        'VCOID --> VCCore
        OIDI --> CoreI
        OIDH --> CoreH
        OIDV --> CoreV

    }

    [DID API] as DID  #Green

    [KMS Interface] as KMS #Green
    [Vault Interface] as Vault #Green

}

'App --> ASDK
KMSM -|> KMS
KMSW -|> KMS
VaultM -|> Vault
VaultW --|> Vault
AppM -> OIDH
AppW -> OIDI
AppW -> OIDV
App -> DID
'AppW -> DID




@enduml