@startuml
'https://plantuml.com/component-diagram
'left to right direction

package "ASDK" as ASDK {

    package VC {


        [Core] as VCCore #Green

        package "VC Formats" as VCF {
            [VC API] as VCAPI #Green
            [SD-JWT VC] as SDJWT #Green
            [W3C VC JSON-LD] as W3C1 #Green
            [W3C VC JSON-LD BBS+] as W3C2  #Green
            [W3C VC JWT] as W3C3 #Orange
            [AnonCreds] as W3C4 #Orange
            SDJWT --|> VCAPI
            W3C1 --|> VCAPI
            W3C2 --|> VCAPI
            W3C3 -|> VCAPI
            W3C4 -|> VCAPI
        }

        package "VC Exchange" {
            [OID4VC] as VCOID #Green
            [Aries] as Aries #Orange
        }

    }

    package DID {
        [DID Resolver Interface] as DIDI #Green
        [Universal DID Resolver] as DIDU #Green
        [did:key] as DIDK #Green
        [did:web] as DIDW #Green
        [did:peer] as DIDP #Green
        DIDK ---|> DIDI
        DIDW --|> DIDI
        DIDP --|> DIDI
        DIDU ---|> DIDI
    }

    package pluggable {
        [KMS Interface] as KMS #Green
        [Vault Interface] as Vault #Green
    }

    package "DIDComm Protocols" as DIDCommPack {
        [DIDComm] as DIDComm #Green
        [Protocols] as DIDCommP  #Orange
        DIDCommP --> DIDComm
    }

    package "Test/Demo Impls" {
        [Askar KMS] as AKMS #Green
        [Askar Vault] as AVault #Green
        [In Memory KMS] as MemKMS  #Green
        [In Memory Vault] as MemVault #Green
        KMS <|--- AKMS
        KMS <|-- MemKMS
        Vault <|-- AVault
        Vault <|-- MemVault
    }
}

VCCore -> VCF
VCOID --> VCCore
Aries --> VCCore
Aries --> DIDComm


note top of ASDK: Green - already implemented;\nOrange - later versions


@enduml