@startuml

title
    DRAFT: Issue Credential flow (+ Persona Integration)
    *Authorization Code Flow w/ Pushed authorization code*
end title

autonumber

actor "User" as User
box Client
participant "Mobile App" as MA
participant "ASDK(Holder)" as ASDKH

box SSI server
participant "Issuer API" as IAPI #lightBlue
participant "ASDK(Issuer)" as ASDKI #lightBlue

box AuthN/AuthZ
participant "Authorization Server (KeyCloak)" as Authz

box 3rd Party
participant "Persona API" as PAPI #lightGreen


User->MA: Request Credential
...
MA->ASDKH: ASDK.facade.Holder.start_issuance(iss_url)
ASDKH->IAPI: GET /.well-known/openid-credential-issuer
IAPI->ASDKI: oid4vc.Issuer.metadata()
IAPI<--ASDKI: metadata
ASDKH<--IAPI: metadata
ASDKH->ASDKH: oid4vc.Holder.from_metadata(metadata)

alt Credential type selection (out-of-band for ASDK)
ASDKH-->MA: propose credentials ([cred_type])
MA-->User: interaction
User->MA: chosen cred type
end
...
MA->ASDKH: ASDK.facade.Holder.select_credentials(cred_type)

ASDKH->ASDKH: oid4vc.Holder.pushed_authz(scope)
ASDKH->Authz: POST /op/par
ASDKH<--Authz: auth_url
ASDKH-->MA: auth_url

alt User's authentication (out-of-band for ASDK)
MA-->User: interaction
User->Authz: Authenticate using auth_url(w/ basic creds)
MA<--Authz: authz_code
end

...
MA->ASDKH: ASDK.facade.Holder.proceed(authz_code)

ASDKH->ASDKH: oid4vc.Holder.exchange_code(authz_code)
ASDKH->Authz: POST /token
Authz-->ASDKH: token
ASDKH->ASDKH: create cred_request
ASDKH->MA: using native KMS via interface in ASDK

alt Open wallet/vault
MA-->User: interaction
User->MA: chosen key
end

MA-->ASDKH: key_handle
ASDKH->ASDKH: oid4vc.Holder.req_credential(token,key_handle,cred_request)
ASDKH->ASDKH: generate proof of possesion (using key_handle)
ASDKH->IAPI: POST /credential
IAPI->ASDKI: oid4vc.Issuer.issue_credential(token, cred_request)
ASDKI<-->Authz: oid4vc.Issuer.validate_token(token)
ASDKI->ASDKI: oid4vc.Issuer.validate_request(cred_request)
ASDKI->ASDKI: oid4vc.Issuer.verify_proof(cred_request.proof)

alt Persona integration (out-of-band for ASDK)
IAPI->PAPI: POST /validate
PAPI-->IAPI: ticket_id
IAPI->IAPI: manage deferred state
end

IAPI-->ASDKH: transaction_id
ASDKH->ASDKH: create poll call/subscribe to push notification
ASDKH-->MA: callback/subscription
...
...
alt Persona integration (out-of-band for ASDK)
IAPI->PAPI: GET /status\n (ticket_id)
PAPI-->IAPI: validated (persona_status)
end
IAPI->IAPI: generate cred_material
IAPI->ASDKI: oid4vc.Issuer.issue_credential(key_handle, cred_material)
ASDKI->ASDKI: vault.save(transaction_id, cred_req, ticket_id, cred, persona_status)
...
...
...
MA->ASDKH: ASDK.facade.Holder.poll_credential(transaction_id))
ASDKH->ASDKH: oid4vc.Holder.deferred_credential(token,transaction_id)
ASDKH->IAPI: POST /deferred_credential
IAPI->ASDKI: vault.get(transaction_id)
ASDKI-->IAPI: credential
IAPI-->ASDKH: vault.store(credential)
ASDKH-->MA: credential received

...
...


@enduml