@startuml
'https://plantuml.com/sequence-diagram

autonumber

actor Holder as H
participant Issuer as I
participant Verifier as V

autonumber 0
I -> I: create `CredentialDefinition`

...

autonumber 1.1
I -> I: <b>offer_credential</b>(cred_def_id, protocol_data)
I --> H: <out-of-band>: send `CredentialOffer`

...

autonumber 2.1
H -> H: <b>request_credential</b>(credential_offer, nonce)
H --> I: <out-of-band>: send `CredentialRequest`

...

autonumber 3.1
I -> I: <b>issue_credential</b>(credential_request, claims, nonce)
I --> H: <out-of-band>: send `(Credential, CredentialMetadata)`
autonumber 4
H -> H: <b>store_credential</b>(credential, credential_metadata)

...

autonumber 5.1
V -> H: <out-of-band>: send `PresentationDefinition`

alt Auto-select credentials
autonumber 5.2.1
H -> H: <b>create_presentation_auto</b>(presentation_input, nonce, verifier_id)

else User selects/approves credentials for the presentation
autonumber 5.2.1
H -> H: <b>find_vcs_for_presentation</b>(presentation_input)
H --> H: <out-of-band>: Select/Approve selection
H -> H: <b>create_presentation</b>(presentation_input, credential, nonce, verifier_id)
end
autonumber 5.3
H -> V: <out-of-band>: send `Presentation`
...

autonumber 6
V -> V: <b>verify_presentation</b>(\n    presentation_input, nonce, presentation)

@enduml