[package]
name = "askar"
version = "0.1.0"
edition = "2024"
rust-version = "1.97.0"
license = "Apache-2.0"


[dependencies]
serde_json = "1.0.120"
serde = { version = "1.0.217", features = ["derive"] }
equs-credentials-sdk = { path = "../.." }
aries-askar = { git = "https://github.com/equs-ai/askar.git", rev = "23361f5b" }
async-trait = "0.1.81"
ecdsa = "0.16.9"
bip32 = "0.5.2"
p256 = "0.13.2"
snafu = "0.8.4"
uuid = { version = "1.10.0", features = ["v4"] }
tracing = { version = "0.1.40", features = ["attributes", "release_max_level_debug"] }
sha2 = "0.10.8"
base64 = "0.22.1"
zeroize = "1.8.1"
rstest = "0.26.1"
rand = "0.9.2"

[dev-dependencies]
tokio = { version = "1.25.0", features = ["macros"] }
equs-credentials-sdk = { path = "../..", features = ["test-utils"] }
