name: CI dev build

on:
  pull_request:
  push:
    branches: [main, test/ci-debian-refactor]
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:

  build-dev:
    uses: ./.github/workflows/_job.yml
    with:
      cache-key: build-dev
      restore: target-dev
      save: target-dev
      run: cargo build --all-features --workspace --exclude wasm
